### ISSUE TITLE
hfs3 internet page : operation timeout

### ISSUE THREAD

**Issue by accnetdev** [rejetto/hfs#437]
Win11
HFS3 0.51.0beta9

On my internet page I see operation timeout.

**Comment by rejetto** [comment]
i think i've found what was causing it.
you told me you'd be out for a while, so let me know if/when you want to try the solution.

**Comment by accnetdev** [comment]
Ok, I will do it.



Le mer. 10 janv. 2024, 17:54, Massimo Melina ***@***.***> a
écrit :

**Comment by accnetdev** [comment]
Back from my trip, ready to test a new version of hfs tomorrow.
Good evening.

**Comment by rejetto** [comment]
any update?

**Comment by accnetdev** [comment]
Hi, this is what I get using your last alpha version :

![20240205_1946_RYZ9MINI_eproust_scsht_001](https://github.com/rejetto/hfs/assets/32092909/9b405f0f-8ade-4b5e-844f-3cd2fcda7d5d)

**Comment by rejetto** [comment]
thanks for reporting
do you have a modem?
do you have upnp enabled?

**Comment by accnetdev** [comment]
My internet box is a Freebox Delta fiber on which Upnp IGD version 1 is
activated.

Le lun. 5 févr. 2024, 23:51, Massimo Melina ***@***.***> a
écrit :

**Comment by rejetto** [comment]
do you confirm the error is displayed after a long time, something like 20 seconds?

**Comment by accnetdev** [comment]
Yes.

Le mar. 6 févr. 2024, 12:18, Massimo Melina ***@***.***> a
écrit :

**Comment by accnetdev** [comment]
At work using the last stable version :

![20240206_1605_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/9af534ff-e048-45a7-a3d9-054338c4ef66)

**Comment by accnetdev** [comment]
Tested at work (behind UTM Sophos XGS) it is the same with alpha version the server address is not the good one :

![20240206_1620_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/3bb1ab73-cc98-4831-bbd5-104666db6bf7)

**Comment by rejetto** [comment]
can you confirm that AT WORK clicking on "port unknown" it says "UPnP is NOT available" ?

**Comment by rejetto** [comment]
[hfs-windows.zip](https://github.com/rejetto/hfs/files/14184104/hfs-windows.zip) this test version  tries to address both problems. Would be cool if you could try it

**Comment by accnetdev** [comment]
First, yes it says "UPnP is NOT available" at work.

![20240207_0930_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/b3fbed75-59aa-4361-b516-71a5ce44a61e)

**Comment by rejetto** [comment]
thanks, can you confirm upnp is NOT enabled on your modem/router?

**Comment by accnetdev** [comment]
Nothing found in Management Software (see routing tabs in screenshot). UPnP could not be implemented in Sophos XGS.

https://community.sophos.com/utm-firewall/f/management-networking-logging-and-reporting/73552/upnp

https://community.sophos.com/sophos-xg-firewall/f/discussions/134072/sophos-xg-and-tailscale

https://assets.sophos.com/X24WTUEQ/at/jnj39v694b8svx9xjp8hq4q/sophos-firewall-brfr.pdf

![20240207_1104_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/f76d6a3d-3993-45a7-affb-abdada72552d)

**Comment by rejetto** [comment]
that's fine, so there's nothing wrong with hfs not finding upnp.
you also say that it should find ip 172.*.
What IPs are actually displayed by HFS ?
you can see them in the console, or clicking "change" button in address.

**Comment by accnetdev** [comment]
It can't connect to admin, does not find page.
https://localhost/~/admin/

if I replace it by the IP 172.50.1.12
https://172.50.1.12/~/admin/
Now using the version you send me it says : Not found

With the stable and the other beta it worked to go in admin with : https://172.50.1.12/~/admin/

**Comment by rejetto** [comment]
are you saying that https://localhost/~/admin/ is not working for you?

**Comment by accnetdev** [comment]
Yes, at work with stable or beta.
I get a browser error.

**Comment by rejetto** [comment]
what error?

**Comment by accnetdev** [comment]
![20240208_1127_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/4d2c56f4-547b-4896-98e0-eb17d3ab9fa8)

and if i replace localhost by 172.50.1.12 :
![20240208_1129_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/c96ed5e0-5281-4843-8328-70fbf0239dfb)

**Comment by rejetto** [comment]
you have some really weird behavior, so i guess something went wrong while making that zip, sorry.
Hopefully this is better https://github.com/rejetto/hfs/files/14228746/hfs-windows.zip
just installed this myself ;)

**Comment by rejetto** [comment]
is there still any problem or should i close this?
you don't need to install the last link if you have 0.52.0-beta4

**Comment by accnetdev** [comment]
Hi Massimo,
Sounds better, it seems to be fixed AT WORK. Congratulations!

![20240221_1529_001_NIPOGIINFO_emmanuel proust](https://github.com/rejetto/hfs/assets/32092909/a0d13433-5b93-4d94-96e2-571c951e17e7)

I have to check AT HOME, I will do it soon and go back to you.
Thanks a lot.

**Comment by accnetdev** [comment]
Hi,
AT HOME, on any browser first I get Operation timeout, after about 2 ou 3 minutes if I refresh I finish to get the correct information.

We could state that this issue is fixed.

The only really bad issue AT WORK is that the admin URL containing localhost does not work, I still have to replace localhost by the local ip in the network to get the admin page. Do I have to create another topic?

**Comment by rejetto** [comment]
yes, another topic please, as that seems a very different problem.
I'm still not ok with you getting the timeout, tho.
