### ISSUE TITLE
Regression: Files and folders "Not Found" under reverse proxy

### ISSUE THREAD

**Issue by soleofthesea** [rejetto/hfs#589]
Regarding bug #585 that was fixed...  unfortunately now I'm unable to access my files via NGINX, completely.

I haven't changed any configs, and the server can be reached, but it's simply returning this instead of what should be the login prompt:

![image](https://github.com/rejetto/hfs/assets/35699509/b466581d-a853-4a62-94e0-d9ee3f5fdd79)

Logging in works, but still returns largely the same page.

**Comment by rejetto** [comment]
What version are you using?

**Comment by soleofthesea** [comment]
Latest one, 0.52.6.

**Comment by rejetto** [comment]
Can you tell me if the problem is present with previous .5?

**Comment by soleofthesea** [comment]
Problem is not present in 0.52.5.

**Comment by rejetto** [comment]
can you send me your nginx and hfs configuration?
you can do it privately if you want a@rejetto.com

**Comment by soleofthesea** [comment]
Wait, what reason? The only changes I made, if you can call it that, is to insert the sample https://github.com/rejetto/hfs/wiki/Reverse-proxy .

**Comment by rejetto** [comment]
how am i supposed to investigate your problem?
reverse proxy works well on my computer

**Comment by rejetto** [comment]
wait, maybe i've found something

**Comment by soleofthesea** [comment]
I just very quickly spun up a fresh Ubuntu VM and was able to reproduce the bug. So I don't think my config is the source?

**Comment by rejetto** [comment]
are you running hfs as binary (no npx) on linux?

the problem depended on the HFS' configuration, that's why it didn't show up on mine.
i have the fix and tested it myself, but I would like you to try and confirm it's good for you too.

**Comment by soleofthesea** [comment]
No, I'm running via npx.

**Comment by rejetto** [comment]
ok, by running npx hfs@exp
you will run the fixed version.
do you mind having a look at it?
just as en extra pair of eyes on it.
otherwise i will just go ahead

**Comment by soleofthesea** [comment]
Still not working, unfortunately...

**Comment by rejetto** [comment]
does your version say 0.52.7-rc1 ?

**Comment by soleofthesea** [comment]
![image](https://github.com/rejetto/hfs/assets/35699509/ccb6da13-5876-4553-be36-637d9e8874a5)

**Comment by rejetto** [comment]
that's weird.
the problem i just fixed was related to using or not "roots" feature.
now i tested with both situation and works for me.
<img width="431" alt="image" src="https://github.com/rejetto/hfs/assets/1367199/069d4909-a8f1-41de-833a-16d2c216ddde">

now i have NO clue on your problem.
you can consider sending me your conf.
and thanks for test!

**Comment by soleofthesea** [comment]
Ah, I see what may be the issue - I should've specified the bug ONLY appears if you use a reverse proxy. I also have no problems if I access directly, although again I point out it worked/works fine with 0.52.5.

**Comment by rejetto** [comment]
that was already clear, the screenshot i posted is of the reverse proxy.
last problem was of "roots" + proxy

**Comment by rejetto** [comment]
i've been experimenting and maybe i've found how to reproduce the problem on my side

**Comment by soleofthesea** [comment]
Okay, here's a copy of the [.hfs](https://github.com/rejetto/hfs/files/15286971/hfs.zip) and [nginx](https://github.com/rejetto/hfs/files/15286972/nginx.zip) folders from that VM I spun up (and verified the bug).

Terminal commands I used, for reference in case there was something I forgot to type
  `sudo apt install nginx`
  `sudo apt install npx`
  `sudo systemctl start nginx`
  `npx hfs`

If it's still not reproducable then I'm stumped.

**Comment by rejetto** [comment]
thanks but as i said on my post, I already reproduced the problem and i'm producing the fix.
it was another thing in my hfs config

**Comment by rejetto** [comment]
ok, i just published another hfs@exp
now it is 0.52.7-rc2
would you give me a feedback, if you can?

**Comment by soleofthesea** [comment]
Well, the good news is that the main functionality of browsing files is back;

But the redirect feature is still not quite right. If you omit the leading slash it's also missing in the URL, so it's `example.com/filesFiles` when it should be `example.com/files/Files`.

**Comment by rejetto** [comment]
i see, thanks for reporting.
i'm looking into it.

**Comment by rejetto** [comment]
ok, i just published another hfs@exp
now it is 0.52.7-rc3
would you give me a feedback, if you can?
thanks for your patience

**Comment by soleofthesea** [comment]
No, thank _you_ for the awesome free app.
So far seems to be fine; no issues on my end.

**Comment by rejetto** [comment]
thank you for your feedback!
published as hfs@latest
