### ISSUE TITLE
Cannot successfully change password as user

### ISSUE THREAD

**Issue by charettepa** [rejetto/hfs#612]
**BEFORE**

**To Reproduce**
1. Login
2. Go to your user settings
3. Click change password
4. Enter new password when prompted then again in the second box
5. Screen returns to main screen
6. Logout
7. Attempt to login with new credentials
8. Login fails

**Describe the bug**
system accepts password change for user
but does not seem to commit it
config.yaml remains unchanged and can only login with old credentials
this used to work at least 1-2 versions ago

changing in accounts using the server admin GUI does change it successfully

**Expected behavior**

for the password change to successfully commit

**Screenshots**
Try to provide videos or else screenshots to help explain your problem.

**Environment (please complete the following information):**
 - OS: Windows 2019
 - HFS Version 0.52.7
 - Browser Chrome, Edge, Brave

**Additional context**
This was working in an older version of 0.52.x

**Comment by rejetto** [comment]
thanks for reporting!
in my tests, the latest (non-beta) version working is 0.51.4.
latest 0.53 is not affected.
keep you posted

**Comment by rejetto** [comment]
fixed in 0.52.8
any feedback appreciated!

**Comment by charettepa** [comment]
upgraded to 0.52.8
attempted to change password in GUI while logged in
Unfortunately it still does not change and config file remains the same

changing in the Server ADMIN GUI
is working but not while logged din as a user

**Comment by charettepa** [comment]
upgraded to 0.52.8

at first it dd not seem to work
however after a forced ctrl+f5 and a cache/cookie clear
it is now working
thank you

**Comment by charettepa** [comment]
Follow up
some users still have issues

We have determined that it works fine in Chrome and Brave
but still fails to work in Edge

we tested on non-up to date versions of Edge 
and on newest Version 125.0.2535.92 (Official build) (64-bit)
we tested with and without incognito
with complete wipe of cookies and site data
Edge consistently fails to proceed

what we have noticed IS
when it work a popup dialogue comes up and says "Password Successfully Changed"
then return you to your profile screen with option to logout or change password
when it fails, there is no popup, no message, and you are exited from your profile
then returned to the main window

**Comment by rejetto** [comment]
ok i reproduced the problem with Edge.
keep you posted.

**Comment by charettepa** [comment]
> ok i reproduced the problem with Edge. keep you posted.

ok thankyou

2nd follow up

it is still happening randomly in Brave
I also tried in firefox and it also works randomly in firefox

**Comment by rejetto** [comment]
ok, i should have fixed it.
find below release candidate 1 for 0.52.9
[hfs-windows.zip](https://github.com/user-attachments/files/15779203/hfs-windows.zip)
to install it, i suggest that you go to Admin/Home an right click on "check for updates", so that you can just paste this link.
Any feedback is appreciated

**Comment by charettepa** [comment]
This now works in all browsers

as an added bonus
when changing the password and entering it in the second time
you can now hit ENTER and it accepts it and continues
previously you had to use the mouse to click continue

**Comment by rejetto** [comment]
cool!
it was always meant to be that way, but the bug prevented it.
