### ISSUE TITLE
problem with hidden files in Windows

### ISSUE THREAD

**Issue by rejetto** [rejetto/hfs#637]
Hello @rejetto 
I see exactly the same problem with hidden files in Windows in versions 0.52.9 and 0.53.0-rc12

_Originally posted by @AntonioD2 in https://github.com/rejetto/hfs/discussions/502#discussioncomment-9813492_

**Comment by rejetto** [comment]
thanks for reporting!
this preview version should fix the problem
[hfs-windows.zip](https://github.com/user-attachments/files/15897179/hfs-windows.zip)

**Comment by rejetto** [comment]
fixed in https://github.com/rejetto/hfs/releases/tag/v0.53.0-rc13

**Comment by anton-polo** [comment]
Hello @rejetto Unfortunately the problem is not completely fixed.
Try to use space in folder and file names when testing.
![image](https://github.com/rejetto/hfs/assets/45563035/9da8a307-da17-4729-921c-de14aa4b59a3)
Test Folder3 and Test File3.rar are folder and file with hidden attribute, but they are displayed in HFS.
![image](https://github.com/rejetto/hfs/assets/45563035/aedbc783-409f-45d2-824c-1d2cab66f0e5)

**Comment by anton-polo** [comment]
To add. This link does not work in this version 0.53.0 rc13
https://192.168.0.1/~/admin/#/plugins
When i opening it, the screen blinks and then goes black.
I checked in Chrome 126.0.6478.61 & 109.0.5414.168.

**Comment by rejetto** [comment]
thanks for reporting, i'll check it asap

**Comment by rejetto** [comment]
ok, problem fixed in next release.
Thanks for reporting!

**Comment by rejetto** [comment]
you can now update to 0.53.0-rc14

**Comment by anton-polo** [comment]
Thank you, 0.53.0-rc14 works correctly with hidden folder and files
