### ISSUE TITLE
Setting Sytem Integration on Linux throws an error

### ISSUE THREAD

**Issue by CygaLV** [rejetto/hfs#696]
**BEFORE**

- Are you using a reverse-proxy, like nginx?
  - no

**To Reproduce**
1. Go to 'HFS Admin Panel' -» 'Shared Files'
2. Click on 'Sytem Integration'
3. Enter an absolute path in the popup
4. Click on 'Continue'

**Describe the bug**
Impossible to add an absolute path to be monitored by the System Integration 

**Expected behavior**
System monitors the absolute path indicated

**Screenshots**
Error message appears after setting a path and clicking continue with message : 

Error: spawn reg ENOENT at ChildProcess._handle.onexit (node:internal/child_process:286:19) at onErrorNT (node:internal/child_process:484:16) at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Environment (please complete the following information):**
 - OS: Raspi Debian 64bits bookworm
 - HFS Version: 0.53
 - Browser: Chrome

**Additional context**

**Comment by rejetto** [comment]
thanks for reporting!
"system integration" is not about monitoring, and it's not available on linux.
The real bug here is that you see the button, while you shouldn't.

**Comment by rejetto** [comment]
fixed in 0.53.1

**Comment by LiveG24** [comment]
Hi Massimo,
just to report that I can still see the system integration button on 0.54.0 beta6 with chrome browser
and server running on macos
EDIT:
I think happened also with alpha4 and beta5.x

thanks ;-)

**Comment by rejetto** [comment]
:FACEPALM:

**Comment by rejetto** [comment]
> Hi Massimo, just to report that I can still see the system integration button on 0.54.0 beta6 with chrome browser and server running on macos EDIT: I think happened also with alpha4 and beta5.x

it's limited to beta version, yes.
fixed in next beta.

**Comment by LiveG24** [comment]
super 🔝
